- name: taking the loops 
  hosts: localhost 
  became: yes 
  # vars:
  # vars_files:
  # vars_prompt:
  # - name: 
  #   prompt: 
  #   private 
  tasks:
  - name: looping the statements 
    ansible.builtin.package: 
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    
