---
- name: loops
  hosts: localhost 
  become: yes
  tasks:
  - name: loppoing the names
    ansible.builtin.debug:
      msg: "this is {{item}}"
    when: "{{item}"} != uday
    loop:
    - uday
    - raju