---
- name: multi variables 
  hosts: localhost
  vars_files: varfromfiles.yaml
  tasks:
  - name: printing the message
    # vars:
    #   name: "ranga"
    #   year: "2024"
    ansible.builtin.debug:
      msg: "my name is {{name}} and i  graduated in the year of {{year}}" 